required:
  - route
  - name
properties:
  route:
    type: string
    x-fern-audiences: ['public']
  name:
    type: string
    x-fern-audiences: ['public']
  billing_tag:
    type: string
    x-fern-audiences: ['public']
  model_id:
    type: string
    x-fern-audiences: ['public']
  model_size:
    type: string
    x-fern-audiences: ['public']
  finetune_id:
    type: string
    x-fern-audiences: ['public']
  endpoint_type:
    type: string
    x-fern-audiences: ['public']
  model_type:
    type: string
    x-fern-audiences: ['public']
  nemo_model_id:
    type: string
    x-fern-audiences: ['public']
  model_url:
    type: string
    x-fern-audiences: ['public']
  context_length:
    type: integer
    x-fern-audiences: ['public']
  serving_framework:
    type: string
    x-fern-audiences: ['public']
  serving_entrypoint:
    type: string
    x-fern-audiences: ['public']
  compatible_endpoints:
    type: array
    x-fern-audiences: ['public']
    items:
      type: string
      x-fern-audiences: ['public']
  prompt_templates:
    type: object
    x-fern-audiences: ['public']
    additionalProperties:
      type: string
      x-fern-audiences: ['public']
  compression_values:
    type: object
    x-fern-audiences: ['public']
    additionalProperties:
      type: number
      x-fern-audiences: ['public']
  compatibility_version:
    type: integer
    x-fern-audiences: ['public']
  default_language:
    type: string
    x-fern-audiences: ['public']
  additional_languages:
    type: string
    x-fern-audiences: ['public']
  labels:
    type: array
    x-fern-audiences: ['public']
    items:
      type: string
      x-fern-audiences: ['public']
  multi_label:
    type: boolean
    x-fern-audiences: ['public']
  baseline_model:
    type: string
    x-fern-audiences: ['public']
  is_baseline:
    type: boolean
    x-fern-audiences: ['public']
  tokenizer_id:
    type: string
    x-fern-audiences: ['public']
  end_of_sequence_string:
    type: string
    x-fern-audiences: ['public']
  streaming:
    type: boolean
    x-fern-audiences: ['public']
  group:
    type: string
    x-fern-audiences: ['public']
  model_version:
    type: string
    x-fern-audiences: ['public']
